### ISSUE TITLE
config should be deep merge

### ISSUE THREAD

**Issue by puttpotsawee** [nodeframe/config-resolver#1]
Hi,
I have an issue about the environment merge,
I dont know why the implementation is done thisway
but my suggestion is, the environment config merge should be done in `deepMerge` function

for example, I have this config in `common.js`

    database: {
      host: 'localhost'
    }

and then, I want the database in production environment to look like this,

    database: {
      host: 'localhost'
      db_options: {
        replSet: {
          rs_name: 'yoyo'
        }
      }
    }

currently if I add this in `production.js`

    database: {
      db_options: {
        replSet: {
          rs_name: 'yoyo'
        }
      }
    }

the config will return this

    database: {
      db_options: {
        replSet: {
          rs_name: 'yoyo'
        }
      }
    }

which I think it should deep merge with the common to return something like this:

    database: {
      host: 'localhost'
      db_options: {
        replSet: {
          rs_name: 'yoyo'
        }
      }
    }

**Comment by thakerng** [comment]
garbage in = garbage out

**Comment by thakerng** [comment]
take a look at 2.0.1
